import turtle
TT = turtle.Turtle()
TT.pensize(5)
TT.color("blue")
TT.penup()
TT.goto(-110, -25)
TT.pendown()
TT.circle(45)
TT.color("black")
TT.penup()
TT.goto(0, -25)
TT.pendown()
TT.circle(45)
TT.color("red")
TT.penup()
TT.goto(110, -25)
TT.pendown()
TT.circle(45)
TT.color("yellow")
TT.penup()
TT.goto(-55, -75)
TT.pendown()
TT.circle(45)
TT.color("green")
TT.penup()
TT.goto(55, -75)
TT.pendown()
TT.circle(45)
turtle.done()